# Generated by Django 5.2.12 on 2026-03-08 17:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "certificate_id",
                    models.CharField(
                        help_text="Формат: XXXXX-XXXXX-XXXXX-XXXXX",
                        max_length=23,
                        unique=True,
                        verbose_name="ID сертификата",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Домен"
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        db_index=True, max_length=12, verbose_name="ИНН/БИН"
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Действует с")),
                (
                    "valid_to",
                    models.DateField(db_index=True, verbose_name="Действует до"),
                ),
                (
                    "users_count",
                    models.PositiveIntegerField(verbose_name="Кол-во пользователей"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Стоимость сертификата в рублях",
                        max_digits=10,
                        null=True,
                        verbose_name="Стоимость",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("paid", "Оплачен"),
                            ("free", "Бесплатный"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Создан"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "request_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Email для запросов",
                    ),
                ),
                (
                    "contacts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список контактов: [{name, email}]",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сертификат",
                "verbose_name_plural": "Сертификаты",
                "db_table": "web_certificates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificateHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Создан"),
                            ("updated", "Изменён"),
                            ("dates_updated", "Даты изменены"),
                            ("deactivated", "Деактивирован"),
                            ("activated", "Активирован"),
                            ("verified", "Проверен"),
                        ],
                        max_length=50,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата"
                    ),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Детали"),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        db_column="certificate_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="cert_manager.certificate",
                        to_field="certificate_id",
                        verbose_name="Сертификат",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись истории",
                "verbose_name_plural": "История сертификатов",
                "db_table": "web_certificate_history",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("expiry_2m", "За 2 месяца до истечения"),
                            ("expiry_1m", "За 1 месяц до истечения"),
                            ("created", "Создание сертификата"),
                            ("updated", "Изменение сертификата"),
                        ],
                        max_length=20,
                        verbose_name="Тип уведомления",
                    ),
                ),
                (
                    "valid_to_date",
                    models.DateField(
                        blank=True,
                        help_text="Для expiry-уведомлений: к какому valid_to относится",
                        null=True,
                        verbose_name="Дата истечения на момент уведомления",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Отправлено"
                    ),
                ),
                (
                    "recipients",
                    models.TextField(
                        help_text="Через запятую", verbose_name="Получатели"
                    ),
                ),
                ("success", models.BooleanField(default=True, verbose_name="Успешно")),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="Ошибка"),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="cert_manager.certificate",
                        verbose_name="Сертификат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "db_table": "web_notification_log",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["domain", "is_active"], name="web_certifi_domain_05682e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["inn", "is_active"], name="web_certifi_inn_4f6727_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["is_active", "valid_to"], name="web_certifi_is_acti_bc32ab_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationlog",
            constraint=models.UniqueConstraint(
                fields=("certificate", "notification_type", "valid_to_date"),
                name="unique_notification_per_period",
            ),
        ),
    ]
